### ISSUE TITLE
Integration with navigation-compose

### ISSUE THREAD

**Issue by fornewid** [fornewid/material-motion-compose#27]
It is expected that transition animations can be applied to navigation-compose after some time.
The following link is related to this.
- https://issuetracker.google.com/issues/172112072

Then, it seems that it needs to be changed to a form that can be combined with navigation-compose.

**Comment by itsandreramon** [comment]
Excited for this one.

**Comment by fornewid** [comment]
Jetpack Navigation team is working for this.
https://android-review.googlesource.com/c/platform/frameworks/support/+/1754655

**Comment by fornewid** [comment]
Maybe a new library will be added to accompanist..? 👀 
https://github.com/google/accompanist/pull/574

**Comment by pblinux** [comment]
accompanist v0.16.0 now includes support for animations in navigation 🥳 🎉

We can use `EnterTransition` and `ExitTransition` with the new `AnimatedNavHost`

```kotlin
val navController = rememberAnimatedNavController()

AnimatedNavHost(
    navController = navController,
    startDestination = SessionStep.Welcome.route,
    enterTransition = { _, _ ->
        materialSharedAxisX(forward = true, slideDistance = 30).enter.transition
    },
    exitTransition = { _, _ ->
        materialSharedAxisX(forward = false, slideDistance = 30).exit.transition
    }
) {
    // Our composables can have individual transitions too
}
```
