### ISSUE TITLE
Navigation Usage sample does not work?

### ISSUE THREAD

**Issue by jonschmidt** [fornewid/material-motion-compose#70]
## Describe the bug
The navigation sample usage does not actually work, as `rememberSlideDistance()` cannot be called from the lambda, it needs to be in a composable function

## To Reproduce
Implement the usage sample

## Expected behavior
It works

**Comment by fornewid** [comment]
Fixed in version [0.7.1](https://github.com/fornewid/material-motion-compose/releases/tag/0.7.1).

Now you don't need `rememberSlideDistance()`.
Remove `rememberSlideDistance()` or declare `Dp` value.
