### ISSUE TITLE
navigation.navigateUp() returns to first route instead the previous route

### ISSUE THREAD

**Issue by uragiristereo** [fornewid/material-motion-compose#85]
## Describe the bug
On v0.7.4, the back press behavior issue is fixed but when using `navigation.navigateUp()` it still occured.

## To Reproduce
I have 3 routes, for example: `splash, main, search`. When i'm navigating `splash -> main -> search`, i called `navigation.navigateUp()` on `search`. It returns to `main` then `splash` reappears again.

## Expected behavior
The `splash` route should not reappears after calling `navigation.navigateUp()` on `search`.

## Environment
 - Android OS version: Android 10
 - Device: Xiaomi Mi A2
 - material-motion-compose version: 0.7.4

**Comment by fornewid** [comment]
First, thanks for report.

If you have a reproducible sample project, please share to me.
I'll check this tonight. :)

**Comment by uragiristereo** [comment]
After investigating the problem. Turns out that i made a mistake in a child composable that makes the function `navigation.navigateUp()` called more than once in my project.

I have already fixed it now. Sorry for the concern.

**Comment by fornewid** [comment]
I'm glad the issue has been resolved.
Have a good day!
